services:
  - type: web
    name: local-services-site
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: PROVIDER_PASSWORD
        sync: false
      - key: DISABLE_AUTH
        value: "0"
    disk:
      name: data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1